---
output: 
  html_document: 
    css: document.css
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  # pour l'énoncé
  # echo=FALSE, eval=FALSE
  # pour la correction
  echo=TRUE, eval=TRUE
)
options(stringsAsFactors=TRUE)
```

# Principal Components Analysis

```{r}
meteo <- read.csv("meteo/monthly.csv")
head(meteo)

# numeric columns
d <- subset(meteo, select=pressure:precipitations)

pairs(d)
cor_matrix <- cor(d, use="pairwise.complete.obs", method="pearson")
cor_matrix

abs(cor_matrix)>0.5
```


```{r}
# PCA
library("FactoMineR")
pca_res <- PCA(d, graph=FALSE)
plot(pca_res, choix="var")
# study correlations

plot(pca_res, choix="ind")
# big mess

# how many axes to look at
str(pca_res, 2)
plot(pca_res$eig$eigenvalue)

# criterion to select the number of "significant" eigen values

# Kaiser-Guttman
abline(h=1, col="red")
# NB: eigenvalues are scaled so that the average eigenvalue is 1. the average eigenvalue is 1

# Broken stick
broken_stick <- function(p){
  result <- c()
	for(j in 1:p){
		E <- 0
		for(x in j:p) E <- E+(1/x)
		result[j] <- E/p
	}
	return(result)
}

bs <- broken_stick(ncol(d)) * sum(pca_res$eig$eigenvalue)
points(bs, col="red")
# -> axes 1+2, surely, 3 possibly, 4 eventually, > 5 = no

plot(pca_res, axes=c(1,2), choix="var")
plot(pca_res, axes=c(2,3), choix="var")
plot(pca_res, axes=c(3,4), choix="var")
# -> actually most of what is important is on 1-2, 3 serves to separate windspeed and precipitations
```

```{r}
# other variables

# identify each observation uniqely
row.names(d) <- paste(meteo$station, meteo$year, meteo$month, sep="_")
pca_res <- PCA(d, graph=FALSE)
plot(pca_res, choix="ind")
# -> spatial structure? 

d <- subset(meteo, select=c(station, pressure:precipitations))
pca_res <- PCA(d, graph=FALSE, quali.sup=1)
pars <- par(no.readonly=TRUE)
par(mfrow=c(1,2))
plot(pca_res, choix="var")
plot(pca_res, choix="ind")
plot(pca_res, choix="var")
plot(pca_res, choix="ind", invisible="ind")

d <- subset(meteo, select=c(month, pressure:precipitations))
pca_res <- PCA(d, graph=FALSE, quali.sup=1)
par(mfrow=c(1,2))
plot(pca_res, choix="var")
plot(pca_res, choix="ind", invisible="ind")

d <- subset(meteo, select=c(year,pressure:precipitations))
pca_res <- PCA(d, graph=FALSE, quali.sup=1)
par(mfrow=c(1,2))
plot(pca_res, choix="var")
plot(pca_res, choix="ind", invisible="ind")
# -> dominated by season
#    2014+2015: warmed and/or less humid

d <- subset(meteo, select=c(low_clouds, pressure:precipitations))
pca_res <- PCA(d, graph=FALSE, quali.sup=1)
par(mfrow=c(1,2))
plot(pca_res, choix="var")
plot(pca_res, choix="ind", invisible="ind")
# -> dominated by season
#    2014+2015: warmed and/or less humid

```

```{r}
# PCs are new variables that can be interpreted and plotted
meteo$PC1 <- pca_res$ind$coord[,1]
meteo$PC2 <- pca_res$ind$coord[,2]
meteo$date <- as.Date(meteo$date)

# only one figure now
par(mfrow=c(1,1), oma=c(0,0,0,4))
palette(hcl(seq(15, 345, length.out=nlevels(meteo$station)), c=100, l=65))

plot(PC1 ~ date, data=meteo, col=meteo$station,
  ylab=expression("warm and dry" %->% ""), pch=16)
legend(
  x=par("usr")[2], y=par("usr")[4], bty="n", xpd=NA,
  legend=levels(meteo$station), col=1:nlevels(meteo$station), pch=16
)

plot(PC2 ~ date, data=meteo, col=meteo$station,
  ylab=expression("rainy and windy" %->% ""), pch=16)
legend(
  x=par("usr")[2], y=par("usr")[4], bty="n", xpd=NA,
  legend=levels(meteo$station), col=1:nlevels(meteo$station), pch=16
)

# simpler and much nicer :-(
library("ggplot2")
qplot(date, PC1, colour=station, data=meteo, geom="line") + ylab(expression("warm and dry" %->% ""))
qplot(date, PC2, colour=station, data=meteo, geom="line") + ylab(expression("rainy and windy"  %->% ""))
```

